import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";
import { QueryProvider } from "@/components/providers/query-provider";

const Open = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Synapsechat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn (Open.className, "bg-white dark:bg-[#313338]")}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        storageKey="synapsechat-theme"
        >
          <ModalProvider/>
          <QueryProvider>
          {children}
          </QueryProvider>  
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
